name: 'projeto_dados'
version: '1.0'
config-version: 2

profile: noticias

# Diretórios onde os modelos SQL estão localizados
model-paths: ["models/economia", "models/governo"]

# Configurações de materialização padrão para os modelos
models:
  projeto_dados:
    +materialized: view  # Pode ser 'view', 'table', 'incremental', etc.
